"""add uuid column to bookings

Revision ID: 4caf8dd637c1
Revises: 
Create Date: 2026-01-20 14:15:21.326133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caf8dd637c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('uuid', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('ticket_slot', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('ticket_type', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('ticket_price', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bookings_uuid'), 'bookings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_uuid'), table_name='bookings')
    op.drop_column('bookings', 'ticket_price')
    op.drop_column('bookings', 'ticket_type')
    op.drop_column('bookings', 'ticket_slot')
    op.drop_column('bookings', 'uuid')
    # ### end Alembic commands ###
