"""Add seat_number and qr_code to bookings

Revision ID: b5ed2ecb161f
Revises: 20260120_add_seat_and_qr_to_bookings
Create Date: 2026-01-20 15:22:04.789117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ed2ecb161f'
down_revision: Union[str, Sequence[str], None] = '20260120_add_seat_and_qr_to_bookings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
