"""Add seat_number and qr_code to bookings

Revision ID: d058d9fc9999
Revises: 4caf8dd637c1
Create Date: 2026-01-20 14:53:15.437208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd058d9fc9999'
down_revision: Union[str, Sequence[str], None] = '4caf8dd637c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('seat_number', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('qr_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'qr_code')
    op.drop_column('bookings', 'seat_number')
    # ### end Alembic commands ###
